alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'
alias browse_to_rstudio="distrobox-host-exec xdg-open http://localhost:8787"

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export PATH=$PATH:$HOME/.local/bin:$HOME/bin
